baseURL: "https://hugo-profile.netlify.app"
languageCode: "en-us"
title: "CU learn"
theme: "hugo-profile"

Paginate: 3
disqusShortname: gurusabarish
googleAnalytics: G-DWJJVE27WD

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1



    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "CU Learn"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/logo1.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    disableThemeToggle: false
    # defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Thawatchai Kwanmueang"
    subtitle: "Welcome to my exhibition site."
    content: "This website is a presentation of the work in the data visualization course."
    image: /images/me2.jpg
    button:
      enable: true
      name: "Resume"
      url: "#"
      download: true
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: "https://github.com/ThawatchaiML"
        - icon: fab fa-instagram
          url: "https://www.instagram.com/thawatchai.tae/"
      

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/me3.png"
    content: |-
      **Name** : Thawatchai Kwanmueang\
      **Nickname** : Tae\
      **Age** : 29\
      **My birthday** : 30 / 12 / 1993

      &emsp;I am a cheerful person and love to help others. But when working, be a serious person. in order to get the job done. Learning new knowledge is my favorite thing.
    skills:
      enable: true
      title: "The program I can do is as follows :"
      items:
        - "Word"
        - "Excel"
        - "PPT"
        - "Canva"
        - "SPSS"
        - "R"

 
  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: Good Visualization
        content: good information visualization It must be able to display information that does not confuse the viewer. The presentation must allow the viewer to know what the creator wants to communicate.
        image: /images/projects/Good Visualization.jpg
        featured:
          name: Read
          link: http://localhost:4321/blogs/good-vis/
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        
      - title: หลักการออกแบบ Data Visualization
        content: The concept of visual design of data consists of 3 components 1)Communicative 2)beautiful 3)reliable
        image: /images/projects/หลักการออกแบบ.jpg
        featured:
          name: Read
          link: http://localhost:4321/blogs/data-visualization/
        # badges:
        #   - "Django"
        #   - "Bootstrap"

      - title: ggplot2
        content: Presenting data using ggplot2 package.
        image: /images/projects/GGPLOT.jpg
        featured:
          name: Read
          link: http://localhost:4321/blogs/ggplot2/
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
       

  #Contact
  contact:
    enable: true
    #title: "Custom name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: tae-thawatchai@hotmail.com
    btnName: Mail me

  footer:
    # recentPosts: false
    socialNetworks:
      github: "https://github.com/ThawatchaiML"
      instagram: "https://www.instagram.com/thawatchai.tae/"
      facebook: "https://www.facebook.com/taethawatchai.kwanmuean"
